name: task_management_setu
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
#  Firebase
  firebase_core:
  cloud_firestore:
  firebase_messaging:
  flutter_local_notifications: ^18.0.1
#  Local DB
  sqflite: ^2.3.3+1
#  Network calling
  flutter_bloc: ^8.1.6
# utils
  intl: ^0.18.0
  google_fonts: ^6.1.0
  fluttertoast: ^8.2.4
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

