// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyD-3OhfRd4LjD5sWpaC0IWhoBicN2PY9xI",
    appId: "1:138874890075:web:65cd1687dff3c769e75c7e",
    authDomain: "task-management-setu.firebaseapp.com",
    messagingSenderId: "138874890075",
    measurementId: "G-TGQ7JHC9QD",
    projectId: "task-management-setu",
    storageBucket: "task-management-setu.firebasestorage.app",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyD-3OhfRd4LjD5sWpaC0IWhoBicN2PY9xI",
    appId: "1:138874890075:web:65cd1687dff3c769e75c7e",
    messagingSenderId: "138874890075",
    projectId: "task-management-setu",
    storageBucket: "task-management-setu.firebasestorage.app",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyD-3OhfRd4LjD5sWpaC0IWhoBicN2PY9xI",
    appId: "1:138874890075:web:65cd1687dff3c769e75c7e",
    messagingSenderId: "138874890075",
    projectId: 'go-camle-fd912',
    storageBucket: "task-management-setu.firebasestorage.app",
  );
}
